### ISSUE TITLE
main.cpp / docs?

### ISSUE THREAD

**Issue by lakenen** [salkj/palette#1]
Hey! I wanted to try this project out, but I noticed there's no main.cpp in the repo. Could you include it or give an example of how to use your library? Also, info on dependencies (i.e., what version of CImg) would be nice too. :)

**Comment by salkj** [comment]
Good point, I didn't expect this project to garner any attention. I'll have it updated within the next few hours.

**Comment by lakenen** [comment]
Thanks! I got it working, but it'd still be nice if anyone else happens across this project! :+1:

**Comment by salkj** [comment]
Issue resolved
